apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres-metrics
    type: postgres
    access: proxy
    url: postgres-metrics:5432
    database: metrics
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: false
    editable: true
